In [1]:
import numpy as np

## Generating arrays from python lists

In [2]:
lst = [
    [1,2,3],
    [3,4,6],
    [3,55,67]
]

In [3]:
type(lst)

list

In [4]:
np_arr = np.array(lst)

In [5]:
np_arr

array([[ 1,  2,  3],
       [ 3,  4,  6],
       [ 3, 55, 67]])

In [6]:
np_arr.shape

(3, 3)

In [7]:
print(np_arr)

[[ 1  2  3]
 [ 3  4  6]
 [ 3 55 67]]


In [8]:
type(np_arr)

numpy.ndarray

In [9]:
len(np_arr)

3

In [10]:
np.size(np_arr)

9

## Generating arrays using builtin fns like arange, linspace

In [11]:
x = np.arange(0,100,2) # doesn't include

In [12]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [13]:
z = np.zeros((5,5),dtype= np.uint8) # rows,col or height,width or y,x

In [14]:
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [15]:
y = np.linspace(-10,10,10)  # start point, end point(included) , number of points we want

In [16]:
y

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [17]:
y.shape

(10,)

In [18]:
O = np.ones((3,8))

In [19]:
O

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
I = np.eye(5)

In [21]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Generating random arrays using builtin fns


In [22]:
r = np.random.rand(2,5,3) # picks a random no from 0 and 1 using a unif distr ; pass shape withut parenthesis

In [23]:
r

array([[[0.10278596, 0.91868865, 0.63818529],
        [0.72582063, 0.39466422, 0.67924135],
        [0.62756583, 0.52666303, 0.10367511],
        [0.10194719, 0.15324257, 0.62983351],
        [0.58618635, 0.36032876, 0.06318927]],

       [[0.52554171, 0.89766983, 0.91861932],
        [0.79513383, 0.46397106, 0.12757176],
        [0.4640233 , 0.04366457, 0.41465685],
        [0.40832031, 0.94638744, 0.0104671 ],
        [0.01260619, 0.65474297, 0.69383779]]])

In [24]:
n = np.random.randn(2,3) # picks vals from a std normal distr

In [25]:
n

array([[ 1.78605459,  0.70699863,  0.80317184],
       [ 0.24848449, -0.52744297,  0.14921153]])

In [26]:
i = np.random.randint(100,2000,(4,5))  # (4,5) is optional

In [27]:
i

array([[ 842, 1748,  404,  780,  184],
       [1953,  314, 1977, 1686,  108],
       [ 914, 1563, 1349, 1190, 1398],
       [ 839, 1057, 1474,  123,  439]])

In [29]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [30]:
arr = np.arange(0,25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr = arr.reshape(5,5)

In [33]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ran = 100*np.random.rand(5,5)

In [39]:
ran

array([[51.07473026, 41.74110031, 22.21078105, 11.98653673, 33.76151714],
       [94.29097039, 32.3202932 , 51.87906217, 70.30189589, 36.36296024],
       [97.17820827, 96.24472949, 25.17822958, 49.72485059, 30.08783098],
       [28.48404944,  3.68869474, 60.9564334 , 50.26790232,  5.14787512],
       [27.86464642, 90.8265886 , 23.95618907, 14.48948721, 48.94527603]])

In [40]:
np.max(ran)

97.17820827209607

In [41]:
np.argmax(ran)

10

In [42]:
np.max(ran, axis =0) # axis = 0 means vertical

array([97.17820827, 96.24472949, 60.9564334 , 70.30189589, 48.94527603])

In [43]:
np.argmax(ran, axis =0) # axis = 0 means vertical

array([2, 2, 3, 1, 4], dtype=int64)

In [44]:
np.max(ran, axis =1) # axis = 1 means horizontal

array([51.07473026, 94.29097039, 97.17820827, 60.9564334 , 90.8265886 ])

In [46]:
ran.dtype

dtype('float64')

## Understanding Shapes

In [60]:
r = np.arange(0,25,2)

In [61]:
print(r)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [62]:
r.shape # it is (13,)

(13,)

In [63]:
r2 = np.expand_dims(r,axis=0)

In [69]:
r2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24]])

In [70]:
r2.shape

(1, 13)

In [66]:
r3 = np.expand_dims(r,axis=1)

In [67]:
print(r3)

[[ 0]
 [ 2]
 [ 4]
 [ 6]
 [ 8]
 [10]
 [12]
 [14]
 [16]
 [18]
 [20]
 [22]
 [24]]


In [68]:
r3.shape

(13, 1)

In [72]:
x2 = np.squeeze(r2)

In [73]:
x2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [74]:
x2.shape

(13,)

In [75]:
x3 = np.squeeze(r3)

In [76]:
x3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [77]:
x3.shape

(13,)

## Numpy Indices and indexing

In [94]:
x = np.random.randn(5,5)

In [96]:
x

array([[-0.77282521, -0.23681861, -0.48536355,  0.08187414,  2.31465857],
       [-1.86726519,  0.68626019, -1.61271587, -0.47193187,  1.0889506 ],
       [ 0.06428002, -1.07774478, -0.71530371,  0.67959775, -0.73036663],
       [ 0.21645859,  0.04557184, -0.65160035,  2.14394409,  0.63391902],
       [-2.02514259,  0.18645431, -0.66178646,  0.85243333, -0.79252074]])

In [97]:
x[:,2]

array([-0.48536355, -1.61271587, -0.71530371, -0.65160035, -0.66178646])

In [100]:
x[1:,:]

array([[-1.86726519,  0.68626019, -1.61271587, -0.47193187,  1.0889506 ],
       [ 0.06428002, -1.07774478, -0.71530371,  0.67959775, -0.73036663],
       [ 0.21645859,  0.04557184, -0.65160035,  2.14394409,  0.63391902],
       [-2.02514259,  0.18645431, -0.66178646,  0.85243333, -0.79252074]])

In [101]:
x[2,3]

0.6795977489346758

## Broadcasting

In [102]:
x = np.reshape(np.arange(1,101),(10,10))

In [103]:
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [104]:
x+20

array([[ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
       [111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

### Very very important : When we slice, that sliced object is still a part of the array. See below!

In [105]:
x_slice = x[2:4,2:4]

In [106]:
x_slice

array([[23, 24],
       [33, 34]])

In [107]:
x_slice[:,:] = 1000

In [108]:
x_slice

array([[1000, 1000],
       [1000, 1000]])

In [109]:
x # see , even x changed!!!

array([[   1,    2,    3,    4,    5,    6,    7,    8,    9,   10],
       [  11,   12,   13,   14,   15,   16,   17,   18,   19,   20],
       [  21,   22, 1000, 1000,   25,   26,   27,   28,   29,   30],
       [  31,   32, 1000, 1000,   35,   36,   37,   38,   39,   40],
       [  41,   42,   43,   44,   45,   46,   47,   48,   49,   50],
       [  51,   52,   53,   54,   55,   56,   57,   58,   59,   60],
       [  61,   62,   63,   64,   65,   66,   67,   68,   69,   70],
       [  71,   72,   73,   74,   75,   76,   77,   78,   79,   80],
       [  81,   82,   83,   84,   85,   86,   87,   88,   89,   90],
       [  91,   92,   93,   94,   95,   96,   97,   98,   99,  100]])

In [110]:
### So, if we want to not have this happen, we need to make copies

x = np.reshape(np.arange(1,101),(10,10)) 

x_copy = np.copy(x)

In [111]:
x_slice = x_copy[2:4,2:4]

In [112]:
x_slice

array([[23, 24],
       [33, 34]])

In [113]:
x_slice[:,:]= 1001111

In [114]:
x_copy

array([[      1,       2,       3,       4,       5,       6,       7,
              8,       9,      10],
       [     11,      12,      13,      14,      15,      16,      17,
             18,      19,      20],
       [     21,      22, 1001111, 1001111,      25,      26,      27,
             28,      29,      30],
       [     31,      32, 1001111, 1001111,      35,      36,      37,
             38,      39,      40],
       [     41,      42,      43,      44,      45,      46,      47,
             48,      49,      50],
       [     51,      52,      53,      54,      55,      56,      57,
             58,      59,      60],
       [     61,      62,      63,      64,      65,      66,      67,
             68,      69,      70],
       [     71,      72,      73,      74,      75,      76,      77,
             78,      79,      80],
       [     81,      82,      83,      84,      85,      86,      87,
             88,      89,      90],
       [     91,      92,      93,   

In [115]:
x  # x would not change now!!

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

## Vectorize

In [120]:
x = np.random.randn(2,2)
squarer = lambda t: str(t).replace(".","-")[:5] # a sample function
vfunc = np.vectorize(squarer)
vfunc(x)

array([['0-096', '0-595'],
       ['-0-81', '2-092']], dtype='<U5')

## Conditional Selection

In [140]:
x = 10*np.random.randn(3,3)

In [141]:
x

array([[ -2.69406834,   7.17542256,  15.02357052],
       [  0.7409478 ,  16.28615546, -13.80101458],
       [-17.03382439,  -0.55547699,   3.84065449]])

In [142]:
x>5

array([[False,  True,  True],
       [False,  True, False],
       [False, False, False]])

In [143]:
x[x>5]

array([ 7.17542256, 15.02357052, 16.28615546])

### Question. In first 2 rows, find indices & values >7

In [144]:
x_copy = np.copy(x)
x_sliced = x_copy[:2,:]
x_sliced

array([[ -2.69406834,   7.17542256,  15.02357052],
       [  0.7409478 ,  16.28615546, -13.80101458]])

In [145]:
x_sliced[x_sliced>7]

array([ 7.17542256, 15.02357052, 16.28615546])

In [134]:
sum(x>5)

array([1, 2, 2])

In [135]:
sum(sum(x>5))

5

In [146]:
np.sum(x>5)  # Just use this method instead of summing like previous

3

In [147]:
np.sum(x>5,axis=1) # we can get axis wise sum as well

array([2, 1, 0])

In [148]:
x = np.arange(1,100,10)

## Arithmetic

In [149]:
x

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [150]:
sum(x>50)

5

In [152]:
x = x.reshape(2,5)

In [153]:
x

array([[ 1, 11, 21, 31, 41],
       [51, 61, 71, 81, 91]])

In [154]:
np.sum(x,axis=1)

array([105, 355])

In [155]:
np.sum(x,axis=0)

array([ 52,  72,  92, 112, 132])

In [158]:
vector = np.arange(1,10,2)

In [159]:
vector

array([1, 3, 5, 7, 9])

In [163]:
vector.shape

(5,)

In [160]:
x+vector  # vector 

array([[  2,  14,  26,  38,  50],
       [ 52,  64,  76,  88, 100]])

In [161]:
np.sqrt(x+vector)

array([[ 1.41421356,  3.74165739,  5.09901951,  6.164414  ,  7.07106781],
       [ 7.21110255,  8.        ,  8.71779789,  9.38083152, 10.        ]])

In [162]:
np.sin(x)

array([[ 0.84147098, -0.99999021,  0.83665564, -0.40403765, -0.15862267],
       [ 0.67022918, -0.96611777,  0.95105465, -0.62988799,  0.10598751]])

In [164]:
x.max()

91

In [165]:
x.min()

1

In [166]:
x.mean()

46.0

In [168]:
x.std(ddof=1) # ddof = 1 refers to sample stdev

30.276503540974915