In [1]:
import numpy as np

### Generating arrays from python lists

In [2]:
lst = [
    [1,2,3],
    [3,4,6],
    [3,55,67]
]

In [3]:
type(lst)

list

In [4]:
np_arr = np.array(lst)

In [5]:
np_arr

array([[ 1,  2,  3],
       [ 3,  4,  6],
       [ 3, 55, 67]])

In [6]:
np_arr.shape

(3, 3)

In [7]:
print(np_arr)

[[ 1  2  3]
 [ 3  4  6]
 [ 3 55 67]]


In [8]:
type(np_arr)

numpy.ndarray

In [9]:
len(np_arr)

3

In [10]:
np.size(np_arr)

9

## Generating arrays using builtin fns like arange, linspace

In [13]:
x = np.arange(0,100,2) # doesn't include

In [14]:
x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [15]:
z = np.zeros((5,5),dtype= np.uint8) # rows,col or height,width or y,x

In [16]:
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=uint8)

In [20]:
y = np.linspace(-10,10,10)  # start point, end point(included) , number of points we want

In [21]:
y

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [22]:
y.shape

(10,)

In [27]:
O = np.ones((3,8))

In [28]:
O

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [23]:
I = np.eye(5)

In [24]:
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Generating random arrays using builtin fns


In [38]:
r = np.random.rand(2,5,3) # picks a random no from 0 and 1 using a unif distr ; pass shape withut parenthesis

In [39]:
r

array([[[0.53849135, 0.30698984, 0.9182665 ],
        [0.17417681, 0.07431932, 0.00843364],
        [0.48746394, 0.07985389, 0.66325441],
        [0.6363132 , 0.23047103, 0.91445459],
        [0.21823908, 0.55364866, 0.18062725]],

       [[0.12609864, 0.82108361, 0.73521132],
        [0.83729259, 0.22608085, 0.87047036],
        [0.21748675, 0.65328054, 0.34947202],
        [0.02289124, 0.02540892, 0.75023654],
        [0.38732757, 0.93188447, 0.40354551]]])

In [41]:
n = np.random.randn(2,3) # picks vals from a std normal distr

In [42]:
n

array([[-0.46760878, -0.5956462 ,  1.1995445 ],
       [ 1.04056617, -0.15286139, -1.34494871]])

In [47]:
i = np.random.randint(100,2000,(4,5))  # (4,5) is optional

In [48]:
i

array([[1378,  572,  861, 1841, 1028],
       [ 672,  235, 1520, 1035, 1442],
       [1710, 1807,  333,  387, 1910],
       [1194,  462,  614,  486, 1154]])